name: Fluent Forms CI

on: 
  push:
    paths:
    - 'fluentforms/**'
  workflow_dispatch:
    
    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    # Cancel any previous runs for the same branch that are still running.
    - name: 'Cancel previous runs'
      uses: styfle/cancel-workflow-action@0.9.0
      with:
        access_token: ${{ github.token }}
    - name: 'Checkout code'
      uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: 'Cache maven dependencies' 
      uses: actions/cache@v2.1.5
      with:
        path: ~/.m2/repository
        key: maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          maven-
    - name: 'Build with Maven'
      run: mvn -B package --file fluentforms

  deploy:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
      - name: Cache maven dependencies 
        uses: actions/cache@v2.1.5
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: | 
              ${{ runner.os }}-maven-
      - name: Deploy to Github Package Registry
        env:
          GITHUB_USERNAME: ${{ secrets.GITHUB_USERNAME }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: mvn -B deploy --file fluentforms --settings fluentforms/settings.xml
