name: Fluent Forms CI

on: 
  push:
    paths:
    - 'fluentforms/**'
    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Cache maven dependencies 
      uses: actions/cache@v1
      with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: | 
              ${{ runner.os }}-maven-
    - name: Build with Maven
      run: mvn -B package --file fluentforms
#
#      run: mvn -B deploy --file fluentforms -Dregistry=https://maven.pkg.github.com/4PointSolutions -Dtoken=GH_TOKEN
#
# produces this error: 
# [ERROR] Failed to execute goal org.apache.maven.plugins:maven-deploy-plugin:2.8.2:deploy (default-deploy) on project fluentforms: 
# Deployment failed: repository element was not specified in the POM inside distributionManagement element or in -DaltDeploymentRepository=id::layout::url parameter -> [Help 1]
