name: Fluent Forms CI

on: 
  push:
    paths:
    - 'fluentforms/**'
    - '.github/workflows/fluentforms-ci.yml'
  workflow_dispatch:
    

jobs:
  build:
    name: Java ${{ matrix.java }} build
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: true
      matrix:
        java: [ 21 ]
        experimental: [false]
        include:
          - java: 24
            experimental: true

    steps:
    - uses: actions/checkout@v5
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v5
      with:
        distribution: 'oracle'
        java-version: ${{ matrix.java }}
        cache: 'maven'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Build with Maven
      run: mvn -B package --file fluentforms

    - name: Publish to GitHub Packages Apache Maven
      if: (github.ref == 'refs/heads/master' || github.ref == 'refs/tags/*') &&  ${{ matrix.experimental }} == 'false' # Only run on main branch or tags and non-experimental
      run: mvn -B deploy -s $GITHUB_WORKSPACE/settings.xml --file fluentforms
      env:
        GITHUB_TOKEN: ${{ github.token }}
