name: REST Services CI

on: 
  push:
    paths:
    - 'rest-services/**'
    - '.github/workflows/rest-services-ci.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21 for Shared Runner
      uses: actions/setup-java@v4
      with:
        distribution: 'oracle'
        java-version: '21'
        cache: 'maven'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Build with Maven
      run: mvn -B package -s $GITHUB_WORKSPACE/settings.xml --file rest-services -P adobe-public
      env:
        GITHUB_TOKEN: ${{ github.token }}

    - name: Publish to GitHub Packages Apache Maven
      if: github.ref == 'refs/heads/master' || github.ref == 'refs/tags/*' # Only run on main branch or tags
      run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml --file rest-services
      env:
        GITHUB_TOKEN: ${{ github.token }}
