name: Spring Sample Web App CI

on: 
  push:
    paths:
    - 'spring/fluentforms-sample-web-app/**'
    - '.github/workflows/spring-sample-web-app-ci.yml'
  workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17 for Shared Runner
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'
        cache: 'maven'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Build Sample Web App with Maven
      run: mvn -B install -s $GITHUB_WORKSPACE/settings.xml --file spring/fluentforms-sample-web-app
      env:
        GITHUB_TOKEN: ${{ github.token }}

#
#
#    - name: Publish Sample Web App to GitHub Packages Apache Maven
#      run: mvn -B deploy -s $GITHUB_WORKSPACE/settings.xml --file spring/fluentforms-sample-web-app
#      env:
#        GITHUB_TOKEN: ${{ github.token }}
  