name: Spring Boot Starter CI

on: 
  push:
    paths:
    - 'spring/fluentforms-spring-boot-**'
    - '.github/workflows/spring-boot-starter-ci.yml'
  workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11 for Shared Runner
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '11'
        cache: 'maven'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Build AutoConfigure with Maven
      run: mvn -B install -s $GITHUB_WORKSPACE/settings.xml --file spring/fluentforms-spring-boot-autoconfigure
      env:
        GITHUB_TOKEN: ${{ github.token }}

    - name: Publish Starter to GitHub Packages Apache Maven
      run: mvn -B deploy -s $GITHUB_WORKSPACE/settings.xml --file spring/fluentforms-spring-boot-starter
      env:
        GITHUB_TOKEN: ${{ github.token }}
  